version: "3.7"
services:

  hikingtrail-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hikingtrail-service
    container_name: hikingtrail-service
    ports:
      - "8080:8080"
    networks:
      - hikingTrail-network

#  mongo-seed:
  ##    build: docker/mongodb-seed
  ##    links:
  ##      - mongodb
  ##    networks:
  ##      - hikingTrail-network

  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: trails
    ports:
      - 27017:27017
    networks:
      - hikingTrail-network

networks:
  hikingTrail-network:
    driver: bridge
