version: "3.7"
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: trails
    ports:
      - 27017:27017
    networks:
      - subscription-network

networks:
  subscription-network:
    driver: bridge
