spring:
  data:
    mongodb:
      username: root
      password: rootpassword
      database: trail
      port: 27017
      host: mongodb
      authentication-database: admin

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.element.hikingTrail: TRACE